### ISSUE TITLE
1 QUESTION, about Plot Pole 4 Life Script

### ISSUE THREAD

**Issue by zgraphz** [RimBlock/Epoch#11]
This part right here really gets me because im not exactly sure what it means to do...

Create a custom folder in the server root directory (the one you have the @mod files in) and copy the contents of the Server folder in to it (you can merge them in to the dayz_server.pbo but need to change the references).

What do i copy? I know it goes in the custom folder but where does the custom folder sit, the server side, client side? main directories? Thank you very much for your time.

Grant M Trefero

**Comment by RimBlock** [comment]
The ARMA server root directory is on the server.

There is only one folder on the ARMA server you have to place the Epoch Server files in to (the @ folders from the Epoch mod).  It also has the arma server exe file in it.

Please ask questions concerning installs in the thread for this mod here (http://epochmod.com/forum/index.php?/topic/11042-release-a-plot-for-life-v25-keep-your-buildables-on-death-take-plot-ownership/) and either myself or others will try to help you out.
